# Generated by Django 3.1 on 2020-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurukul', '0002_auto_20200825_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
