# Generated by Django 3.1 on 2020-09-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gurukul', '0005_auto_20200828_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField()),
                ('resume_url', models.CharField(max_length=500)),
            ],
        ),
    ]
