# Generated by Django 3.1 on 2020-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='resources',
            field=models.FileField(null=True, upload_to='./uploads'),
        ),
    ]
