# Generated by Django 3.1 on 2020-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20200825_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='resource_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
