# Generated by Django 3.1 on 2020-08-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20200825_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='content',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='./uploads'),
        ),
    ]
