# Generated by Django 3.1 on 2020-09-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_assignmentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='assignment/assignments/'),
        ),
    ]
